"use strict";
import { BaseContract, Contract, ContractFactory } from "boaproject-contracts";
import { BigNumber, FixedNumber } from "boaproject-bignumber";
import { Signer, VoidSigner } from "boaproject-abstract-signer";
import { Wallet } from "boaproject-wallet";
import * as constants from "boaproject-constants";
import * as providers from "boaproject-providers";
import { getDefaultProvider } from "boaproject-providers";
import { Wordlist, wordlists } from "boaproject-wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "boaproject-logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map