"use strict";

import { BaseContract, Contract, ContractFactory } from "boaproject-contracts";

import { BigNumber, FixedNumber } from "boaproject-bignumber";

import { Signer, VoidSigner } from "boaproject-abstract-signer";
import { Wallet } from "boaproject-wallet";

import * as constants from "boaproject-constants";

import * as providers from "boaproject-providers";
import { getDefaultProvider } from "boaproject-providers";

import { Wordlist, wordlists} from "boaproject-wordlists";

import * as utils from "./utils";

import { ErrorCode as errors, Logger } from "boaproject-logger";

////////////////////////
// Types

import type { TypedDataDomain, TypedDataField } from "boaproject-abstract-signer";
import { BigNumberish } from "boaproject-bignumber";
import { Bytes, BytesLike, Signature } from "boaproject-bytes";
import { Transaction, UnsignedTransaction } from "boaproject-transactions";


////////////////////////
// Compile-Time Constants

// This is generated by "npm run dist"
import { version } from "./_version";

const logger = new Logger(version);

////////////////////////
// Types

import {
    ContractFunction,
    ContractReceipt,
    ContractTransaction,

    Event,
    EventFilter,

    Overrides,
    PayableOverrides,
    CallOverrides,

    PopulatedTransaction,

    ContractInterface
} from "boaproject-contracts";


////////////////////////
// Exports

export {
    Signer,

    Wallet,
    VoidSigner,

    getDefaultProvider,
    providers,

    BaseContract,
    Contract,
    ContractFactory,

    BigNumber,
    FixedNumber,

    constants,
    errors,

    logger,

    utils,

    wordlists,


    ////////////////////////
    // Compile-Time Constants

    version,


    ////////////////////////
    // Types

    ContractFunction,
    ContractReceipt,
    ContractTransaction,
    Event,
    EventFilter,

    Overrides,
    PayableOverrides,
    CallOverrides,

    PopulatedTransaction,

    ContractInterface,

    TypedDataDomain,
    TypedDataField,

    BigNumberish,

    Bytes,
    BytesLike,

    Signature,

    Transaction,
    UnsignedTransaction,

    Wordlist
};

