 cd ~/Work/boans/ethers.js/packages/abi && npm publish
 cd ~/Work/boans/ethers.js/packages/abstract-provider && npm publish
 cd ~/Work/boans/ethers.js/packages/abstract-signer && npm publish
 cd ~/Work/boans/ethers.js/packages/address && npm publish
 cd ~/Work/boans/ethers.js/packages/asm && npm publish
 cd ~/Work/boans/ethers.js/packages/base64 && npm publish
 cd ~/Work/boans/ethers.js/packages/basex && npm publish
 cd ~/Work/boans/ethers.js/packages/bignumber && npm publish
 cd ~/Work/boans/ethers.js/packages/bytes && npm publish
 cd ~/Work/boans/ethers.js/packages/cli && npm publish
 cd ~/Work/boans/ethers.js/packages/constants && npm publish
 cd ~/Work/boans/ethers.js/packages/contracts && npm publish
 cd ~/Work/boans/ethers.js/packages/ethers && npm publish
 cd ~/Work/boans/ethers.js/packages/experimental && npm publish
 cd ~/Work/boans/ethers.js/packages/hardware-wallets && npm publish
 cd ~/Work/boans/ethers.js/packages/hash && npm publish
 cd ~/Work/boans/ethers.js/packages/hdnode && npm publish
 cd ~/Work/boans/ethers.js/packages/json-wallets && npm publish
 cd ~/Work/boans/ethers.js/packages/keccak256 && npm publish
 cd ~/Work/boans/ethers.js/packages/logger && npm publish
 cd ~/Work/boans/ethers.js/packages/networks && npm publish
 cd ~/Work/boans/ethers.js/packages/pbkdf2 && npm publish
 cd ~/Work/boans/ethers.js/packages/properties && npm publish
 cd ~/Work/boans/ethers.js/packages/providers && npm publish
 cd ~/Work/boans/ethers.js/packages/random && npm publish
 cd ~/Work/boans/ethers.js/packages/rlp && npm publish
 cd ~/Work/boans/ethers.js/packages/sha2 && npm publish
 cd ~/Work/boans/ethers.js/packages/shims && npm publish
 cd ~/Work/boans/ethers.js/packages/signing-key && npm publish
 cd ~/Work/boans/ethers.js/packages/solidity && npm publish
 cd ~/Work/boans/ethers.js/packages/strings && npm publish
 cd ~/Work/boans/ethers.js/packages/testcases && npm publish
 cd ~/Work/boans/ethers.js/packages/tests && npm publish
 cd ~/Work/boans/ethers.js/packages/transactions && npm publish
 cd ~/Work/boans/ethers.js/packages/units && npm publish
 cd ~/Work/boans/ethers.js/packages/wallet && npm publish
 cd ~/Work/boans/ethers.js/packages/web && npm publish
 cd ~/Work/boans/ethers.js/packages/wordlists && npm publish
